# Generated by Django 6.0.4 on 2026-09-30 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=15)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=100)),
                ('orientation', models.CharField(default='horizontal', max_length=20)),
                ('primary_color', models.CharField(default='#1e3a8a', max_length=50)),
                ('preview_style', models.CharField(default='modern', max_length=100)),
                ('sample_company', models.CharField(default='Vertex Solutions Pvt Ltd', max_length=150)),
                ('sample_tagline', models.CharField(default='Engineering Tomorrow', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VisitingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('category_group', models.CharField(choices=[('shapes', 'Shop by Shapes'), ('papers_textures', 'Shop by Papers & Textures'), ('specialty', 'Specialty Business Cards'), ('holders', 'Card Holders & Accessories')], default='shapes', max_length=50)),
                ('dimensions', models.CharField(default='8.9 cm x 5.1 cm', max_length=100)),
                ('gsm', models.CharField(default='300-350 GSM', max_length=50)),
                ('finish_type', models.CharField(default='Matte', max_length=100)),
                ('base_price_100', models.DecimalField(decimal_places=2, default=270.0, max_digits=10)),
                ('min_quantity', models.PositiveIntegerField(default=100)),
                ('rating', models.FloatField(default=4.5)),
                ('reviews_count', models.PositiveIntegerField(default=120)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('accent_color', models.CharField(default='#003366', max_length=50)),
                ('image_gradient', models.CharField(default='linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)', max_length=255)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='catalog.category')),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=100)),
                ('corner_style', models.CharField(default='Standard', max_length=50)),
                ('finish', models.CharField(default='Matte', max_length=50)),
                ('backside', models.CharField(default='Blank', max_length=50)),
                ('custom_name', models.CharField(blank=True, max_length=100)),
                ('custom_title', models.CharField(blank=True, max_length=100)),
                ('custom_company', models.CharField(blank=True, max_length=150)),
                ('custom_phone', models.CharField(blank=True, max_length=50)),
                ('custom_email', models.CharField(blank=True, max_length=100)),
                ('custom_qr_url', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=2.7, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=270.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.visitingcard')),
            ],
        ),
    ]
