# Generated by Django 6.0.4 on 2026-10-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingcard',
            name='category_group',
            field=models.CharField(choices=[('shapes', '1. By Shape'), ('texture', '2. Texture'), ('special', '3. Special'), ('holders', '4. Card Holders'), ('papers_textures', 'Papers & Textures (Legacy)'), ('specialty', 'Specialty (Legacy)')], default='shapes', max_length=50),
        ),
    ]
