# Generated by Django 6.0.4 on 2026-10-01 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_visitingcard_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='catalog.visitingcard'),
        ),
        migrations.AlterField(
            model_name='visitingcard',
            name='badge',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitingcard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='visitingcard',
            name='category_group',
            field=models.CharField(blank=True, default='shapes', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitingcard',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visitingcard',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
