# Generated by Django 6.0.4 on 2026-10-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_template_card_alter_visitingcard_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingcard',
            name='bullet_points',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='image_url',
            field=models.CharField(blank=True, default='/pdp_card_stack.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='image_url_2',
            field=models.CharField(blank=True, default='/pdp_card_box.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='image_url_3',
            field=models.CharField(blank=True, default='/visiting_cards_hero.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='specifications',
            field=models.TextField(blank=True, default=''),
        ),
    ]
