# Generated by Django 6.0.4 on 2026-10-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_visitingcard_bullet_points_visitingcard_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='color_palette',
            field=models.CharField(default='#0056b3,#1e293b,#047857,#dc2626', max_length=255),
        ),
        migrations.AddField(
            model_name='template',
            name='layout_type',
            field=models.CharField(default='classic_photo', max_length=50),
        ),
    ]
