# Generated by Django 6.0.4 on 2026-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_template_color_palette_template_layout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='accent_color',
            field=models.CharField(blank=True, default='#0056b3', max_length=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='preview_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='template_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
