# Generated by Django 6.0.4 on 2026-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_cartitem_accent_color_cartitem_preview_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='back_preview_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
