# Generated by Django 6.0.4 on 2026-10-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_cartitem_back_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='back_background_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='template',
            name='background_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='template',
            name='sample_email',
            field=models.CharField(blank=True, default='contact@example.in', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='sample_job_title',
            field=models.CharField(blank=True, default='Managing Director', max_length=150),
        ),
        migrations.AddField(
            model_name='template',
            name='sample_name',
            field=models.CharField(blank=True, default='Aditya Sharma', max_length=150),
        ),
        migrations.AddField(
            model_name='template',
            name='sample_phone',
            field=models.CharField(blank=True, default='+91 98765 43210', max_length=50),
        ),
        migrations.AddField(
            model_name='template',
            name='text_positions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
