# Generated by Django 6.0.4 on 2026-10-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_template_back_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='color_palette',
            field=models.CharField(blank=True, default='#0056b3,#1e293b,#047857,#dc2626', max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='industry',
            field=models.CharField(blank=True, default='Corporate & Business', max_length=100),
        ),
        migrations.AlterField(
            model_name='template',
            name='layout_type',
            field=models.CharField(blank=True, default='classic_photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='template',
            name='orientation',
            field=models.CharField(blank=True, default='horizontal', max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='preview_style',
            field=models.CharField(blank=True, default='modern', max_length=100),
        ),
        migrations.AlterField(
            model_name='template',
            name='primary_color',
            field=models.CharField(blank=True, default='#1e3a8a', max_length=50),
        ),
        migrations.AlterField(
            model_name='template',
            name='sample_company',
            field=models.CharField(blank=True, default='Vertex Solutions Pvt Ltd', max_length=150),
        ),
        migrations.AlterField(
            model_name='template',
            name='sample_tagline',
            field=models.CharField(blank=True, default='Engineering Tomorrow', max_length=200),
        ),
    ]
