# Generated by Django 6.0.4 on 2026-10-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_template_color_palette_alter_template_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingcard',
            name='badge',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
