import { apiRequest } from './apiClient';
import { fetchCards, fetchCardBySlug } from './cardApi';

export { fetchCards, fetchCardBySlug };

export const fetchProductsByCategory = async (categorySlug = '', search = '') => {
  try {
    const cards = await fetchCards(categorySlug, search);
    if (cards && cards.length > 0) return cards;
  } catch (e) {
    console.warn('fetchProductsByCategory error:', e);
  }

  // Catalog items for all printing categories
  const fallbackProducts = [
    {
      id: 1,
      title: 'Standard Visiting Cards',
      slug: 'visiting-cards',
      category: 'visiting-cards',
      category_group: 'shapes',
      dimensions: '8.9 cm x 5.1 cm',
      gsm: '350 GSM',
      finish_type: 'Matte / Glossy',
      base_price_100: 200.0,
      min_quantity: 100,
      rating: 4.8,
      reviews_count: 1420,
      badge: 'Bestseller',
      tagline: 'Professional high-definition print on sturdy 350 GSM cardstock.',
      description: 'Our most popular business card choice. Perfect for executives, entrepreneurs, and freelancers seeking high durability with brilliant color reproduction.',
      accent_color: '#172046',
      is_featured: true,
    },
    {
      id: 2,
      title: 'Metallic Gold Foil Cards',
      slug: 'gold-foil',
      category: 'visiting-cards',
      category_group: 'special',
      dimensions: '8.9 cm x 5.1 cm',
      gsm: '400 GSM',
      finish_type: 'Velvet Soft Touch + Gold Foil',
      base_price_100: 450.0,
      min_quantity: 100,
      rating: 4.9,
      reviews_count: 650,
      badge: 'Luxury',
      tagline: 'Ultra-luxurious hot foil stamped accents that gleam under light.',
      description: 'Reflective gold foil applied onto rich matte velvet texture. Designed for luxury brands, architects, realtors, and senior executives.',
      accent_color: '#EF1C62',
      is_featured: true,
    },
    {
      id: 3,
      title: 'Outdoor Vinyl Flex Banners',
      slug: 'banners',
      category: 'banners',
      category_group: 'marketing',
      dimensions: '6 ft x 3 ft (Custom Sizes)',
      gsm: '340 GSM Weatherproof Vinyl',
      finish_type: 'UV Resistant Glossy',
      base_price_100: 399.0,
      min_quantity: 1,
      rating: 4.9,
      reviews_count: 512,
      badge: 'Fast Dispatch',
      tagline: 'Heavy-duty weatherproof flex banners with brass eyelets.',
      description: 'High resolution digital printing on durable UV-treated vinyl. Suitable for shop fronts, events, exhibitions, and outdoor promotions.',
      accent_color: '#1C7EE0',
      is_featured: true,
    },
    {
      id: 4,
      title: 'Trifold Corporate Brochures',
      slug: 'brochures',
      category: 'brochures',
      category_group: 'marketing',
      dimensions: 'A4 Folded to DL',
      gsm: '170 GSM Art Gloss Paper',
      finish_type: 'Double-Sided Full Color',
      base_price_100: 650.0,
      min_quantity: 50,
      rating: 4.7,
      reviews_count: 320,
      badge: 'Corporate',
      tagline: 'Multi-fold marketing collateral with crisp folding crease.',
      description: 'Showcase your company profile, service catalogs, and product range in crisp detail on premium glossy art paper.',
      accent_color: '#12A66A',
      is_featured: true,
    },
    {
      id: 5,
      title: 'Custom Screen Printed T-Shirts',
      slug: 't-shirts',
      category: 't-shirts',
      category_group: 'apparel',
      dimensions: 'Sizes S, M, L, XL, XXL',
      gsm: '220 GSM 100% Bio-Washed Cotton',
      finish_type: 'Vibrant Screen / Sublimation',
      base_price_100: 299.0,
      min_quantity: 1,
      rating: 4.9,
      reviews_count: 890,
      badge: 'Trending',
      tagline: 'Premium 100% cotton apparel with long-lasting vibrant prints.',
      description: 'Custom merchandise for company events, sports teams, startups, and college fests with high color fastness and breathable comfort.',
      accent_color: '#EF1C62',
      is_featured: true,
    },
    {
      id: 6,
      title: 'Die-Cut Waterproof Stickers & Labels',
      slug: 'stickers',
      category: 'stickers',
      category_group: 'packaging',
      dimensions: 'Custom Die-Cut Shapes',
      gsm: 'Self-Adhesive Vinyl',
      finish_type: 'Glossy Lamination',
      base_price_100: 199.0,
      min_quantity: 50,
      rating: 4.8,
      reviews_count: 440,
      badge: 'Popular',
      tagline: 'Scratch-resistant waterproof adhesive labels for bottles and packaging.',
      description: 'Precision contour-cut stickers that adhere tightly to glass, cardboard, plastic, and metal surfaces without residue.',
      accent_color: '#F5C542',
      is_featured: false,
    },
    {
      id: 7,
      title: 'Laminated Restaurant Menu Cards',
      slug: 'menu-cards',
      category: 'menu-cards',
      category_group: 'hospitality',
      dimensions: 'A4 / A3 Hardbound or Folded',
      gsm: '350 GSM + Thermal Lamination',
      finish_type: 'Spill-Proof Heavy Matte',
      base_price_100: 349.0,
      min_quantity: 5,
      rating: 4.9,
      reviews_count: 280,
      badge: 'Spill-Proof',
      tagline: 'Tear-proof and washable menu cards with high color vibrancy.',
      description: 'Thick protective lamination that withstands food spills, water, and frequent customer handling in cafes, bars, and restaurants.',
      accent_color: '#172046',
      is_featured: false,
    },
    {
      id: 8,
      title: 'Gallery Wrapped Canvas Prints',
      slug: 'canvas',
      category: 'canvas',
      category_group: 'special',
      dimensions: '12"x18", 18"x24", 24"x36"',
      gsm: '420 GSM Pure Cotton Canvas',
      finish_type: 'Museum Grade Stretched on Wood Frame',
      base_price_100: 599.0,
      min_quantity: 1,
      rating: 4.9,
      reviews_count: 195,
      badge: 'Premium Art',
      tagline: 'Museum-quality archival ink stretched over solid pine wood frames.',
      description: 'Turn your photographs and digital artwork into stunning home and office wall decors with vibrant textured cotton canvas.',
      accent_color: '#EF1C62',
      is_featured: false,
    },
  ];

  if (!categorySlug || categorySlug === 'all') {
    return fallbackProducts;
  }
  return fallbackProducts.filter(
    (p) => p.category === categorySlug || p.category_group === categorySlug || p.slug.includes(categorySlug)
  );
};
